############################ deployment ###################################

replicaCount: 1

image:
  registry: docker.io
  repository: mysql
  tag: 5.7

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort: 3306
                     ################# config ur db using castom envs ###############
dbconfig:
  dbuser: user
  db_user_password: password
  dbrootpassword: password
  dbname: mysql
  dbhost: mysql
  dbdomain: mysql.fiefdomain.com
                     ################# configure ur volumes ###############
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  # selectorLabels: {}
  # subPath: ""
  existingClaim: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
                     ################# configure ur ingress ###############
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
                     ################# configure ur resourses ###############
resources: # {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
                     ################# configure ur autoscaling ###############
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Namespace: wordpress

nodeSelector: {}

tolerations: []

affinity: {}

############################ service ###################################

service:
  type: ClusterIP
  port: 3306