apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
data:
  DB_PASSWORD: {{ .Values.wpconfig.db_user_password | b64enc}}
  WP_USER_NAME: {{ .Values.wpconfig.wpuser | b64enc}}
  DB_HOST: {{ .Values.wpconfig.dbhost | b64enc}}
  DB_NAME: {{ .Values.wpconfig.dbname | b64enc}}